### ISSUE TITLE
prefs file not created on Linux(RPM)

### ISSUE THREAD

**Issue by thomond** [felixrieseberg/macintosh.js#13]
I installed via https://github.com/felixrieseberg/macintosh.js/releases/download/v1.0.2/macintosh.js-1.0.2-1.x86_64.rpm
At bootup it gets stuck at 66.6% and exceptions is logged:
```
BasiliskII-worker-boot.js:209 getPrefs: Failed to set prefs Error: EACCES: permission denied, open '/usr/lib/macintosh.js/resources/app/src/basilisk/prefs'
    at Object.openSync (fs.js:462:3)
    at Object.func [as openSync] (electron/js2c/asar.js:140:31)
    at Object.writeFileSync (fs.js:1283:35)
    at getPrefs (file:///usr/lib/macintosh.js/resources/app/src/basilisk/BasiliskII-worker-boot.js:207:8)
    at startEmulator (file:///usr/lib/macintosh.js/resources/app/src/basilisk/BasiliskII-worker-boot.js:493:29)
    at self.onmessage (file:///usr/lib/macintosh.js/resources/app/src/basilisk/BasiliskII-worker-boot.js:357:5)
...
/usr/lib/macintosh.js/resources/app/src/basilisk/BasiliskII.js:5649 Uncaught Loading data file "prefs" failed.
```
/usr/lib/macintosh.js/resources/app/src/basilisk/prefs did not exist but /usr/lib/macintosh.js/resources/app/src/basilisk/prefs_template did. Copying the template to prefs resolved issue.

Not sure if this is bug or documentation oversight?

**Comment by hcal** [comment]
I can confirm that `sudo cp /usr/lib/macintosh.js/resources/app/src/basilisk/prefs_template /usr/lib/macintosh.js/resources/app/src/basilisk/prefs` does allow the app to run on Fedora 32.

**Comment by felixrieseberg** [comment]
Thanks friends, I'm moving discussion here: https://github.com/felixrieseberg/macintosh.js/issues/18

(Apologies for the bug!)
