### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by DanyMusica** [felixrieseberg/macintosh.js#22]
Uncaught Exception:
Error: Cannot create BrowserWindow before app is ready
    at createWindow (/private/var/folders/30/n5zbf61j6qq4sgjg3vl5tpk00000gn/T/AppTranslocation/62F495A6-76E3-405F-8AD9-9B37685A7687/d/macintosh.js.app/Contents/Resources/app/src/main/windows.js:60:16)
    at App.onActivate (/private/var/folders/30/n5zbf61j6qq4sgjg3vl5tpk00000gn/T/AppTranslocation/62F495A6-76E3-405F-8AD9-9B37685A7687/d/macintosh.js.app/Contents/Resources/app/src/main/index.js:35:5)
    at App.emit (events.js:310:20)

**Comment by DanyMusica** [comment]
Fixed: you have to run the app from the Application folder
