### ISSUE TITLE
Launching macintosh.js doesn't finish and hogs resources in a very old 64-bit W7 HPE SP1 machine.

### ISSUE THREAD

**Issue by antdude** [felixrieseberg/macintosh.js#33]
SquirrelSetup.log shows:
2020-07-29 22:51:34> Program: Starting Squirrel Updater: --install .
2020-07-29 22:51:43> Program: Starting install, writing to C:\Users\tester\AppData\Local\SquirrelTemp
2020-07-29 22:51:50> Program: About to install to: C:\Users\tester\AppData\Local\macintosh
2020-07-29 22:51:58> CheckForUpdateImpl: Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\tester\AppData\Local\macintosh\packages\.betaId'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   at Squirrel.UpdateManager.CheckForUpdateImpl.getOrCreateStagedUserId()
2020-07-29 22:51:58> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\tester\AppData\Local\macintosh\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
2020-07-29 22:51:58> CheckForUpdateImpl: Reading RELEASES file from C:\Users\tester\AppData\Local\SquirrelTemp
2020-07-29 22:52:00> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2020-07-29 22:52:11> ApplyReleasesImpl: Writing files to app directory: C:\Users\tester\AppData\Local\macintosh\app-1.0.3
2020-07-29 22:52:54> LogHost: Rigging execution stub for macintosh.js_ExecutionStub.exe to C:\Users\tester\AppData\Local\macintosh\macintosh.js.exe
2020-07-29 22:54:45> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\tester\AppData\Local\macintosh\app-1.0.3\macintosh.js.exe]
2020-07-29 22:55:06> ApplyReleasesImpl: Couldn't run Squirrel hook, continuing: C:\Users\tester\AppData\Local\macintosh\app-1.0.3\macintosh.js.exe: System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Squirrel.Utility.<>c__DisplayClass11_0.<InvokeProcessAsync>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<InvokeProcessAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass10_0.<<invokePostInstall>b__0>d.MoveNext()
2020-07-29 22:55:06> ApplyReleasesImpl: Starting fixPinnedExecutables
2020-07-29 22:55:07> ApplyReleasesImpl: Examining Pin: Internet Explorer.lnk
2020-07-29 22:55:10> ApplyReleasesImpl: Examining Pin: Windows Explorer.lnk
2020-07-29 22:55:11> ApplyReleasesImpl: Examining Pin: Windows Media Player.lnk
2020-07-29 22:55:11> ApplyReleasesImpl: Fixing up tray icons
2020-07-29 22:55:11> ApplyReleasesImpl: cleanDeadVersions: for version 1.0.3
2020-07-29 22:55:11> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-1.0.3
2020-07-29 22:55:37> InstallHelperImpl: Couldn't write uninstall icon, don't care: System.Net.WebException: The remote name could not be resolved: 'raw.githubusercontent.com'
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.UpdateManager.InstallHelperImpl.<CreateUninstallerRegistryEntry>d__5.MoveNext()

I get a windowed black screen from the program too. Your two EXEs' hog the very old updated 64-bit W7 HPE SP1 PC's single core CPU to the max, and RAM (2 GB) keeps going up to almost 100% used. I downloaded and installed macintoshjs-1.0.3-setup-x64.exe. :(

Thank you for reading and hopefully answering soon. :)

**Comment by felixrieseberg** [comment]
I'm sorry to say that your machine might be a little underpowered - this app was mostly meant as a stunt, some kind of quick hit of nostalgia. It's probably the least performant way to emulate an old Mac out there.

I'd [recommend the original Basilisk II emulator](http://basilisk.cebix.net/). You can even use this disk's disk image with it (which you can find in the installation directory `resources/src/basilisk`.

**Comment by MalEbenSo** [comment]
I hope that the two projects can benefit from each other either way. macintosh.js has already recognized the support from the Basilisk II project. Maybe the feedback here and the thoughts will also inspire Basilisk II especially wrt usability.

On the resource hogging: I run macintosh.js on a 2012 MBP with a Core i7 3520M (2.9 GHz Base, 3.6 GHz Turbo, dual core with additional hyperthreading). The process "macintosh.js Helper (Renderer)" is taking around 100% CPU while the app just sits in the background doing nothing.
